# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=250)),
                ('body', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('targetpost', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
