# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20190212_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No set', max_length=250)),
                ('body', models.TextField()),
                ('postType', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('edited', models.BooleanField(default=False)),
                ('background', models.CharField(default='na2.jpg', max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=250)),
                ('body', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('targetpost', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
