# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190214_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newnotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='numofnewnote',
            field=models.IntegerField(default=0),
        ),
    ]
