# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190216_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='newnotification',
        ),
    ]
